### ISSUE TITLE
Upgrade mistune package

### ISSUE THREAD

**Issue by DLLanesVega** [natl/fractaldna#458]
While trying to run my Jupyter project, I encountered this dependency conflict. Can the mistune dependency be upgraded to the latest version?

![image](https://user-images.githubusercontent.com/132904211/236814966-aa3ddc71-cc61-443b-9ef5-a2144dcc397e.png)

**Comment by natl** [comment]
Mistune is now a dev dependency so that should resolve this. Let me know if it still doesn't work.

#459

**Comment by DLLanesVega** [comment]
Thanks. Issue solved.
